name: fred_economics
channels:
- conda-forge
- defaults
dependencies:
- _openmp_mutex=4.5
- ansi2html=1.9.2
- anyio=4.11.0
- argon2-cffi=25.1.0
- argon2-cffi-bindings=25.1.0
- arrow=1.3.0
- asttokens=3.0.0
- async-lru=2.0.5
- attrs=25.3.0
- babel=2.17.0
- beautifulsoup4=4.13.5
- bleach=6.2.0
- bleach-with-css=6.2.0
- blinker=1.9.0
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- ca-certificates=2025.8.3
- cached-property=1.5.2
- cached_property=1.5.2
- category_encoders=2.7.0
- certifi=2025.8.3
- charset-normalizer=3.4.3
- click=8.3.0
- cloudpickle=3.1.1
- colorama=0.4.6
- comm=0.2.3
- contourpy=1.3.3
- cpython=3.11.13
- cuda-cudart=12.9.79
- cuda-cudart_win-64=12.9.79
- cuda-version=12.9
- cycler=0.12.1
- cython=3.1.4
- dash=2.18.2
- debugpy=1.8.17
- decorator=5.2.1
- defusedxml=0.7.1
- deprecation=2.1.0
- exceptiongroup=1.3.0
- executing=2.2.1
- flask=3.1.2
- flask-cors=3.0.10
- fonttools=4.60.0
- fqdn=1.5.1
- freetype=2.14.1
- glib=2.86.0
- glib-tools=2.86.0
- gst-plugins-base=1.24.11
- gstreamer=1.24.11
- h11=0.16.0
- h2=4.3.0
- hpack=4.1.0
- httpcore=1.0.9
- httpx=0.28.1
- hyperframe=6.1.0
- icu=75.1
- idna=3.10
- imbalanced-learn=0.14.0
- importlib-metadata=8.7.0
- ipykernel=6.30.1
- ipython_pygments_lexers=1.1.1
- ipywidgets=8.1.7
- isoduration=20.11.0
- itsdangerous=2.2.0
- jedi=0.19.2
- jinja2=3.1.6
- joblib=1.3.2
- json5=0.12.1
- jsonpointer=3.0.0
- jsonschema=4.25.1
- jsonschema-specifications=2025.9.1
- jsonschema-with-format-nongpl=4.25.1
- jupyter-dash=0.4.2
- jupyter-lsp=2.3.0
- jupyter_client=8.6.3
- jupyter_core=5.8.1
- jupyter_events=0.12.0
- jupyter_server=2.17.0
- jupyter_server_terminals=0.5.3
- jupyterlab=4.4.7
- jupyterlab_pygments=0.3.0
- jupyterlab_server=2.27.3
- jupyterlab_widgets=3.0.15
- kaleido-core=0.2.1
- khronos-opencl-icd-loader=2024.10.24
- kiwisolver=1.4.9
- krb5=1.21.3
- lark=1.3.0
- lcms2=2.17
- lerc=4.0.0
- libblas=3.9.0
- libboost=1.88.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libclang13=21.1.1
- libdeflate=1.24
- libexpat=2.7.1
- libffi=3.4.6
- libfreetype=2.14.1
- libfreetype6=2.14.1
- libgcc=15.1.0
- libglib=2.86.0
- libgomp=15.1.0
- libhwloc=2.12.1
- libiconv=1.18
- libintl=0.22.5
- libintl-devel=0.22.5
- libjpeg-turbo=3.1.0
- liblapack=3.9.0
- liblightgbm=4.6.0
- liblzma=5.8.1
- libogg=1.3.5
- libpng=1.6.50
- libsodium=1.0.20
- libsqlite=3.50.4
- libtiff=4.7.1
- libvorbis=1.3.7
- libwebp-base=1.6.0
- libwinpthread=12.0.0.r4.gg4f2fc60ca
- libxcb=1.17.0
- libxgboost=3.0.5
- libxml2=2.15.0
- libxml2-16=2.15.0
- libzlib=1.3.1
- lightgbm=4.6.0
- llvm-openmp=20.1.8
- llvmlite=0.44.0
- markupsafe=3.0.2
- mathjax=2.7.7
- matplotlib-inline=0.1.7
- mistune=3.1.4
- mkl=2024.2.2
- munkres=1.1.4
- nbclient=0.10.2
- nbconvert-core=7.16.6
- nbformat=5.10.4
- nest-asyncio=1.6.0
- notebook-shim=0.2.4
- numba=0.61.2
- numpy=1.26.4
- opencl-headers=2025.06.13
- openjpeg=2.5.4
- openssl=3.5.3
- orjson=3.11.3
- overrides=7.7.0
- packaging=25.0
- parso=0.8.5
- patsy=1.0.1
- pcre2=10.46
- pickleshare=0.7.5
- pillow=11.3.0
- pip=25.2
- platformdirs=4.4.0
- plotly=5.24.1
- ply=3.11
- pmdarima=2.0.4
- prometheus_client=0.23.1
- prompt-toolkit=3.0.52
- psutil=7.1.0
- pthread-stubs=0.4
- pure_eval=0.2.3
- py-xgboost=3.0.5
- pycaret=3.3.2
- pygments=2.19.2
- pynndescent=0.5.13
- pyod=2.0.5
- pyparsing=3.2.5
- pyqt=5.15.11
- pyqt5-sip=12.17.0
- pysocks=1.7.1
- python=3.11.13
- python-dateutil=2.9.0.post0
- python-fastjsonschema=2.21.2
- python-kaleido=0.2.1
- python-xxhash=3.5.0
- python_abi=3.11
- pytz=2025.2
- pywin32=311
- pyyaml=6.0.2
- pyzmq=27.1.0
- qhull=2020.2
- qt-main=5.15.15
- referencing=0.36.2
- requests=2.32.5
- retrying=1.4.2
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rfc3987-syntax=1.1.0
- rpds-py=0.27.1
- schemdraw=0.15
- scikit-base=0.7.8
- scikit-learn=1.4.2
- scikit-plot=0.3.7
- scipy=1.11.4
- send2trash=1.8.3
- shap=0.48.0
- sip=6.10.0
- six=1.17.0
- slicer=0.0.8
- sniffio=1.3.1
- soupsieve=2.8
- stack_data=0.6.3
- statsmodels=0.14.5
- tbats=1.1.3
- tbb=2021.13.0
- tenacity=9.1.2
- terminado=0.18.1
- threadpoolctl=3.6.0
- tinycss2=1.4.0
- tk=8.6.13
- toml=0.10.2
- tomli=2.2.1
- tornado=6.5.2
- tqdm=4.67.1
- trace-updater=0.0.9.1
- traitlets=5.14.3
- types-python-dateutil=2.9.0.20250822
- typing-extensions=4.15.0
- typing_extensions=4.15.0
- typing_utils=0.1.0
- ucrt=10.0.26100.0
- umap-learn=0.5.9.post2
- unicodedata2=16.0.0
- uri-template=1.3.0
- urllib3=2.5.0
- vc=14.3
- vc14_runtime=14.44.35208
- vcomp14=14.44.35208
- vs2015_runtime=14.44.35208
- wcwidth=0.2.14
- webcolors=24.11.1
- webencodings=0.5.1
- websocket-client=1.8.0
- werkzeug=3.1.3
- wheel=0.45.1
- widgetsnbextension=4.0.14
- win_inet_pton=1.1.0
- winpty=0.4.3
- wurlitzer=3.1.1
- xgboost=3.0.5
- xorg-libxau=1.0.12
- xorg-libxdmcp=1.1.5
- xxhash=0.8.3
- yaml=0.2.5
- yellowbrick=1.5
- zeromq=4.3.5
- zipp=3.23.0
- zstandard=0.25.0
- zstd=1.5.7
- pip:
  - altair==5.5.0
  - analytics-python==1.4.post1
  - annotated-types==0.7.0
  - anthropic==0.68.0
  - backcall==0.2.0
  - backoff==1.10.0
  - cachetools==5.5.2
  - catboost==1.2.8
  - cffi==2.0.0
  - chardet==5.2.0
  - distro==1.9.0
  - docopt==0.6.2
  - docstring-parser==0.17.0
  - docstring_parser==0.17.0
  - et-xmlfile==2.0.0
  - et_xmlfile==2.0.0
  - fastjsonschema==2.21.2
  - gitdb==4.0.12
  - gitpython==3.1.45
  - google-auth==2.40.3
  - google-genai==1.38.0
  - graphviz==0.21
  - greenlet==3.2.4
  - importlib_metadata==8.7.0
  - ipython==8.12.3
  - jiter==0.11.0
  - jupyter-events==0.12.0
  - kaleido==0.2.1
  - matplotlib==3.7.5
  - mito-ai==0.1.45
  - mito_ai==0.1.45
  - mitosheet==0.2.44
  - mitosheet-helper-pro==0.0.3
  - monotonic==1.6
  - narwhals==2.5.0
  - nbconvert==7.16.6
  - notebook_shim==0.2.4
  - openai==1.109.1
  - openpyxl==3.1.5
  - pandas==2.3.2
  - pandocfilters==1.5.1
  - pipreqs==0.5.0
  - prompt_toolkit==3.0.52
  - protobuf==6.32.1
  - pyarrow==21.0.0
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pyasn1_modules==0.4.2
  - pycparser==2.23
  - pydantic==2.11.9
  - pydantic-core==2.33.2
  - pydantic_core==2.33.2
  - pydeck==0.9.1
  - PyQt5==5.15.11
  - PyQt5_sip==12.17.0
  - python-dotenv==1.1.1
  - python-json-logger==3.3.0
  - pywinpty==3.0.0
  - regex==2025.9.18
  - rsa==4.9.1
  - setuptools==80.9.0
  - smmap==5.0.2
  - sqlalchemy==2.0.43
  - stack-data==0.6.3
  - streamlit==1.50.0
  - tiktoken==0.11.0
  - trace_updater==0.0.9.1
  - typing-inspection==0.4.1
  - tzdata==2025.2
  - unidiff==0.7.5
  - watchdog==6.0.0
  - websockets==15.0.1
  - yarg==0.1.9
  - fredapi
